"""initial migration

Revision ID: 6c49d61bb804
Revises: 
Create Date: 2026-05-09 20:02:10.172500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c49d61bb804'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_roles_id'), 'roles', ['id'], unique=False, schema='auth')
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_location', sa.String(length=150), nullable=False),
    sa.Column('destination_location', sa.String(length=150), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('trip_rate', sa.Float(), nullable=True),
    sa.Column('diesel_limit', sa.Float(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_routes_id'), 'routes', ['id'], unique=False, schema='master')
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('capacity_ton', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('rc_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_number'),
    schema='master'
    )
    op.create_index(op.f('ix_master_vehicles_id'), 'vehicles', ['id'], unique=False, schema='master')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_id'), 'users', ['id'], unique=False, schema='auth')
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_expiry', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['master.vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    schema='master'
    )
    op.create_index(op.f('ix_master_drivers_id'), 'drivers', ['id'], unique=False, schema='master')
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('trip_date', sa.DateTime(), nullable=True),
    sa.Column('trip_status', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('diesel_used', sa.Float(), nullable=True),
    sa.Column('trip_expense', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['master.drivers.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['master.routes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['master.vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index(op.f('ix_operations_trips_id'), 'trips', ['id'], unique=False, schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_trips_id'), table_name='trips', schema='operations')
    op.drop_table('trips', schema='operations')
    op.drop_index(op.f('ix_master_drivers_id'), table_name='drivers', schema='master')
    op.drop_table('drivers', schema='master')
    op.drop_index(op.f('ix_auth_users_id'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_master_vehicles_id'), table_name='vehicles', schema='master')
    op.drop_table('vehicles', schema='master')
    op.drop_index(op.f('ix_master_routes_id'), table_name='routes', schema='master')
    op.drop_table('routes', schema='master')
    op.drop_index(op.f('ix_auth_roles_id'), table_name='roles', schema='auth')
    op.drop_table('roles', schema='auth')
    # ### end Alembic commands ###
